Repository CoreOffice/XMLCoder, pull requests merged in 2020-04, with the labels that each got.

#166 Test w/ Xcode 11.4 on macOS, Swift 5.2.1 on Linux
  .github/workflows/main.yml
  .pre-commit-config.yaml
  Brewfile
  README.md
  Sources/XMLCoder/Decoder/XMLUnkeyedDecodingContainer.swift
  XMLCoder.xcodeproj/project.pbxproj
  azure-pipelines.yml
  pod.sh
  test_xcodebuild.sh
Labels: test suite improvement

#167 Run GitHub Actions on a push to the master branch
  .github/workflows/danger.yml
  .github/workflows/main.yml
Labels: test suite improvement

#170 Fix CDATA issue
  Sources/XMLCoder/Auxiliaries/Box/KeyedBox.swift
  Sources/XMLCoder/Auxiliaries/KeyedStorage.swift
  Tests/XMLCoderTests/CDATATest.swift
Labels: bug

#160 Add support for root attributes propagation
  Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
  Sources/XMLCoder/Encoder/XMLEncoder.swift
  Tests/XMLCoderTests/RootLevetExtraAttributesTests.swift
  XMLCoder.xcodeproj/project.pbxproj
Labels: enhancement

#175 Add TopLevelEncoder implementation
  Sources/XMLCoder/Decoder/XMLDecoder.swift
  Tests/XMLCoderTests/CombineTests.swift
  Tests/XMLCoderTests/XCTestManifests.swift
Labels: enhancement
